"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "am"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Common
    "common.email": "Email",
    "common.password": "Password",
    "common.name": "Name",
    "common.fullName": "Full Name",
    "common.phone": "Phone",
    "common.address": "Address",
    "common.city": "City",
    "common.country": "Country",
    "common.zipCode": "Zip Code",
    "common.submit": "Submit",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Info",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.continue": "Continue",
    "common.finish": "Finish",
    "common.start": "Start",
    "common.stop": "Stop",
    "common.pause": "Pause",
    "common.resume": "Resume",
    "common.restart": "Restart",
    "common.reset": "Reset",
    "common.clear": "Clear",
    "common.close": "Close",
    "common.open": "Open",
    "common.show": "Show",
    "common.hide": "Hide",
    "common.expand": "Expand",
    "common.collapse": "Collapse",
    "common.enable": "Enable",
    "common.disable": "Disable",
    "common.activate": "Activate",
    "common.deactivate": "Deactivate",
    "common.yes": "Yes",
    "common.no": "No",
    "common.ok": "OK",
    "common.done": "Done",
    "common.apply": "Apply",
    "common.confirm": "Confirm",
    "common.reject": "Reject",
    "common.approve": "Approve",
    "common.decline": "Decline",
    "common.accept": "Accept",
    "common.send": "Send",
    "common.receive": "Receive",
    "common.login": "Login",
    "common.logout": "Logout",
    "common.register": "Register",
    "common.forgotPassword": "Forgot Password",
    "common.resetPassword": "Reset Password",
    "common.changePassword": "Change Password",
    "common.verifyEmail": "Verify Email",
    "common.verifyPhone": "Verify Phone",
    "common.verifyOTP": "Verify OTP",
    "common.resendOTP": "Resend OTP",
    "common.bookDemo": "Book Your Demo",
    "common.startFreeTrial": "Start 14-day free trial",
    "common.noCredit": "No credit card needed",
    "common.quickSetup": "Takes less than 15 mins to set up",
    "common.rating": "rating",

    // App
    "app.name": "Rona",
    "app.tagline": "Workforce Management System",

    // Navigation
    "nav.home": "Home",
    "nav.features": "Features",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.login": "Login",
    "nav.register": "Register",
    "nav.terms": "Terms",
    "nav.privacy": "Privacy",
    "nav.back": "Back",

    // Homepage
    "home.hero.title": "Manage your entire factory workforce in one app",
    "home.hero.subtitle":
      "Rona simplifies everyday operations with factory workers and keeps them connected, so you can focus on growing your business",
    "home.features.title": "Features",
    "home.features.subtitle": "Everything you need to manage your factory workforce",
    "home.features.description":
      "Streamline operations, improve communication, and boost productivity with our comprehensive solution",

    // Login
    "login.title": "Login",
    "login.subtitle": "Enter your credentials to access your account",
    "login.email": "Email",
    "login.password": "Password",
    "login.forgotPassword": "Forgot password?",
    "login.noAccount": "Don't have an account?",
    "login.register": "Register",
    "login.selectRole": "Select Role",
    "login.worker": "Worker",
    "login.admin": "Admin",
    "login.owner": "Owner",
    "login.otp": "OTP",
    "login.verifying": "Verifying...",
    "login.loggingIn": "Logging in...",
    "login.verifyAndLogin": "Verify & Login",
    "login.specialAccess": "Special Access",
    "login.kioskMode": "Kiosk Mode",
    "login.saasAdmin": "SAAS Admin",

    // SAAS Admin
    "saasAdmin.title": "SAAS Admin Portal",
    "saasAdmin.subtitle": "Enter your credentials to access the Rona SAAS Admin Portal",
    "saasAdmin.backToLogin": "Back to Login Page",

    // Demo Page
    "demo.title": "Book a Demo",
    "demo.subtitle":
      "See how Rona can transform your factory's workforce management. Our team will walk you through the platform and answer all your questions.",
    "demo.requestTitle": "Request Your Demo",
    "demo.requestSubtitle": "Fill out the form below and we'll contact you to schedule a demo at your convenience.",
    "demo.personalizedDemo": "Personalized Demo",
    "demo.demoDescription": "30-minute session tailored to your factory's specific needs",
    "demo.fullName": "Full Name",
    "demo.email": "Email",
    "demo.companyName": "Company Name",
    "demo.employees": "Number of Employees",
    "demo.message": "Message",
    "demo.phone": "Phone",
    "demo.office": "Office",
    "demo.location": "Addis Ababa, Ethiopia",
    "demo.submitting": "Submitting...",
    "demo.success": "Your demo request has been submitted. We'll contact you soon!",

    // Footer
    "footer.copyright": "© 2025 Rona. All rights reserved.",
    "footer.madeBy": "Made by Negus Marketing",

    // Worker
    "worker.dashboard": "Worker Dashboard",
    "worker.attendance": "Attendance",
    "worker.requests": "Requests",
    "worker.schedule": "Schedule",
    "worker.payroll": "Payroll",
    "worker.profile": "Profile",
    "worker.settings": "Settings",
    "worker.notifications": "Notifications",
    "worker.messages": "Messages",
    "worker.clockIn": "Clock In",
    "worker.clockOut": "Clock Out",
    "worker.leaveRequest": "Leave Request",
    "worker.shiftSwap": "Shift Swap",
    "worker.emergency": "Emergency",
    "worker.nfcCard": "NFC Card",

    // Admin
    "admin.dashboard": "Admin Dashboard",
    "admin.workers": "Workers",
    "admin.shifts": "Shifts",
    "admin.attendance": "Attendance",
    "admin.payroll": "Payroll",
    "admin.reports": "Reports",
    "admin.settings": "Settings",
    "admin.notifications": "Notifications",
    "admin.messages": "Messages",
    "admin.emergency": "Emergency",
    "admin.multiLocation": "Multi-Location",
    "admin.announcements": "Announcements",
    "admin.nfcScan": "NFC Scan",

    // Admin Dashboard
    "admin.welcome": "Welcome to Admin Dashboard",
    "admin.dashboardOverview": "Manage your factory operations and workforce",
    "admin.totalWorkers": "Total Workers",
    "admin.activeEmployees": "Active Employees",
    "admin.todayAttendance": "Today's Attendance",
    "admin.present": "Present",
    "admin.late": "Late",
    "admin.absent": "Absent",
    "admin.openShifts": "Open Shifts",
    "admin.needsStaffing": "Needs Staffing",
    "admin.pendingRequests": "Pending Requests",
    "admin.awaitingApproval": "Awaiting Approval",
    "admin.emergencies": "Emergencies",
    "admin.active": "Active",
    "admin.resolved": "Resolved",
    "admin.responseRate": "Response Rate",
    "admin.emergencyAlerts": "Emergency Alerts",
    "admin.manageAll": "Manage All",
    "admin.respond": "Respond",
    "admin.noActiveEmergencies": "No active emergencies",
    "admin.pendingApprovals": "Pending Approvals",
    "admin.attendanceOverview": "Attendance Overview",
    "admin.todayShifts": "Today's Shifts",
    "admin.reviewRequests": "Review Requests",
    "admin.reviewRequestsDesc": "Approve or deny pending worker requests",
    "admin.requestTypes.leave": "Leave Request",
    "admin.requestTypes.shift-swap": "Shift Swap",
    "admin.requestTypes.overtime": "Overtime",
    "admin.requestedOn": "Requested on",
    "admin.deny": "Deny",
    "admin.approve": "Approve",
    "admin.viewAll": "View All",
    "admin.reviewSelected": "Review Selected",
    "admin.timeSlot": "Time Slot",
    "admin.assigned": "Assigned",
    "admin.checkedIn": "Checked In",
    "admin.manageShift": "Manage Shift",
    "admin.viewDetailedAttendance": "View Detailed Attendance",
    "admin.viewAllShifts": "View All Shifts",
    "admin.shiftCoverage": "Shift Coverage",
    "admin.currentStaffing": "Current staffing levels and understaffed areas",
    "admin.scheduled": "Scheduled",
    "admin.understaffed": "Understaffed",
    "admin.coverageNeeded": "Coverage Needed",
    "admin.eveningShift": "Evening Shift",
    "admin.nightShift": "Night Shift",
    "admin.packaging": "Packaging",
    "admin.maintenance": "Maintenance",
    "admin.needAdditionalWorkers": "Need additional workers",
    "admin.assignWorkers": "Assign Workers",
    "admin.autoAssignAvailableWorkers": "Auto-Assign Available Workers",
    "admin.day": "Day",
    "admin.week": "Week",
    "admin.month": "Month",
    "admin.workerAttendancePatterns": "Worker attendance patterns and trends",
    "admin.onTime": "On Time",
    "admin.high": "High",
    "admin.medium": "Medium",
    "admin.low": "Low",
    "admin.id": "ID",
    "admin.reporter": "Reporter",
    "admin.type": "Type",
    "admin.location": "Location",
    "admin.priority": "Priority",
    "admin.status": "Status",
    "admin.action": "Action",
    "admin.critical": "Critical",
    "admin.inProgress": "In Progress",
    "admin.showing": "Showing",
    "admin.of": "of",
    "admin.totalIncidents": "total incidents",
    "admin.exportReport": "Export Report",
    "admin.machineryMalfunction": "Machinery Malfunction",
    "admin.safetyHazard": "Safety Hazard",
    "admin.powerOutage": "Power Outage",
    "admin.chemicalSpill": "Chemical Spill",
    "admin.assemblyLine": "Assembly Line",
    "admin.packagingArea": "Packaging Area",
    "admin.building": "Building",
    "admin.laboratory": "Laboratory",

    // Owner
    "owner.dashboard": "Owner Dashboard",
    "owner.finances": "Finances",
    "owner.kpi": "KPI",
    "owner.reports": "Reports",
    "owner.settings": "Settings",
    "owner.notifications": "Notifications",
    "owner.messages": "Messages",
    "owner.emergency": "Emergency",
    "owner.inventory": "Inventory",
    "owner.subscription": "Subscription",
    "owner.branding": "Branding",
    "owner.softwareProblem": "Software Problem",
    "owner.nfcScan": "NFC Scan",

    // Worker Profile
    "profile.title": "My Profile",
    "profile.saveChanges": "Save Changes",
    "profile.editProfile": "Edit Profile",
    "profile.workerNotFound": "Worker not found",
    "profile.department": "Department",
    "profile.position": "Position",
    "profile.joinDate": "Join Date",
    "profile.nfcCardId": "NFC Card ID",
    "profile.status.label": "Status",
    "profile.status.active": "Active",
    "profile.status.inactive": "Inactive",
    "profile.status.onLeave": "On Leave",
    "profile.attendanceRate": "Attendance Rate",
    "profile.target": "Target",

    "profile.skills.title": "Skills",
    "profile.skills.machineOperation": "Machine Operation",
    "profile.skills.qualityControl": "Quality Control",
    "profile.skills.teamLeadership": "Team Leadership",

    "profile.tabs.personal": "Personal Info",
    "profile.tabs.employment": "Employment",
    "profile.tabs.qualifications": "Qualifications",
    "profile.tabs.performance": "Performance",

    "profile.personalInfo.title": "Personal Information",
    "profile.personalInfo.description": "Your personal details and contact information",
    "profile.personalInfo.fullName": "Full Name",
    "profile.personalInfo.email": "Email Address",
    "profile.personalInfo.phone": "Phone Number",
    "profile.personalInfo.address": "Address",
    "profile.personalInfo.emergencyContact": "Emergency Contact",
    "profile.personalInfo.languages": "Languages",

    "profile.employment.title": "Employment Details",
    "profile.employment.description": "Your employment information and work history",
    "profile.employment.employeeId": "Employee ID",
    "profile.employment.currentSchedule": "Current Schedule",
    "profile.employment.morningShift": "Morning shift",
    "profile.employment.afternoonShift": "Afternoon shift",
    "profile.employment.nightShift": "Night shift",

    "profile.qualifications.title": "Qualifications & Skills",
    "profile.qualifications.description": "Your education, certifications, and professional skills",
    "profile.qualifications.education": "Education",
    "profile.qualifications.certifications": "Certifications",
    "profile.qualifications.issued": "Issued",
    "profile.education.diploma": "Diploma in Textile Engineering, Addis Ababa Institute of Technology",
    "profile.certifications.workplaceSafety": "Workplace Safety",
    "profile.certifications.machineOperation": "Machine Operation Level 2",
    "profile.languages.amharic": "Amharic",
    "profile.languages.english": "English",
    "profile.languages.oromo": "Oromo",

    "profile.performance.title": "Performance & Attendance",
    "profile.performance.description": "Your performance metrics and attendance records",
    "profile.performance.rating": "Performance Rating",
    "profile.performance.outOf": "out of",
    "profile.performance.lastUpdated": "Last updated",
    "profile.performance.march": "March",
    "profile.performance.attendanceSummary": "Attendance Summary",
    "profile.performance.present": "Present",
    "profile.performance.late": "Late",
    "profile.performance.absent": "Absent",
    "profile.performance.recentAttendance": "Recent Attendance",
    "profile.performance.date": "Date",
    "profile.performance.checkIn": "Check In",
    "profile.performance.checkOut": "Check Out",
    "profile.performance.status": "Status",

    "profile.toast.updated": "Profile updated",
    "profile.toast.updatedDescription": "Your profile information has been updated successfully.",
  },
  am: {
    // Common
    "common.email": "ኢሜይል",
    "common.password": "የይለፍ ቃል",
    "common.name": "ስም",
    "common.fullName": "ሙሉ ስም",
    "common.phone": "ስልክ",
    "common.address": "አድራሻ",
    "common.city": "ከተማ",
    "common.country": "ሀገር",
    "common.zipCode": "ዚፕ ኮድ",
    "common.submit": "አስገባ",
    "common.cancel": "ሰርዝ",
    "common.save": "አስቀምጥ",
    "common.delete": "ሰርዝ",
    "common.edit": "አስተካክል",
    "common.view": "እይ",
    "common.search": "ፈልግ",
    "common.filter": "አጣራ",
    "common.sort": "አስቀምጥ",
    "common.loading": "በመጫን ላይ...",
    "common.error": "ስህተት",
    "common.success": "ተሳክቷል",
    "common.warning": "ማስጠንቀቂያ",
    "common.info": "መረጃ",
    "common.back": "ተመለስ",
    "common.next": "ቀጣይ",
    "common.previous": "ቀዳሚ",
    "common.continue": "ቀጥል",
    "common.finish": "ጨርስ",
    "common.start": "ጀምር",
    "common.stop": "አቁም",
    "common.pause": "አቁም",
    "common.resume": "ቀጥል",
    "common.restart": "እንደገና ጀምር",
    "common.reset": "ዳግም አስጀምር",
    "common.clear": "አጽዳ",
    "common.close": "ዝጋ",
    "common.open": "ክፈት",
    "common.show": "አሳይ",
    "common.hide": "ደብቅ",
    "common.expand": "አስፋ",
    "common.collapse": "ሰብስብ",
    "common.enable": "አንቃ",
    "common.disable": "አሰናክል",
    "common.activate": "አንቃ",
    "common.deactivate": "አሰናክል",
    "common.yes": "አዎ",
    "common.no": "አይ",
    "common.ok": "እሺ",
    "common.done": "ተጠናቅቋል",
    "common.apply": "ተግብር",
    "common.confirm": "አረጋግጥ",
    "common.reject": "ውድቅ አድርግ",
    "common.approve": "ፍቀድ",
    "common.decline": "ውድቅ አድርግ",
    "common.accept": "ተቀበል",
    "common.send": "ላክ",
    "common.receive": "ተቀበል",
    "common.login": "ግባ",
    "common.logout": "ውጣ",
    "common.register": "ይመዝገቡ",
    "common.forgotPassword": "የይለፍ ቃል ረሳኽ?",
    "common.resetPassword": "የይለፍ ቃል ዳግም አስጀምር",
    "common.changePassword": "የይለፍ ቃል ቀይር",
    "common.verifyEmail": "ኢሜይል አረጋግጥ",
    "common.verifyPhone": "ስልክ አረጋግጥ",
    "common.verifyOTP": "OTP አረጋግጥ",
    "common.resendOTP": "OTP እንደገና ላክ",
    "common.bookDemo": "ዴሞ ይያዙ",
    "common.startFreeTrial": "የ14 ቀን ነፃ ሙከራ ይጀምሩ",
    "common.noCredit": "የክሬዲት ካርድ አያስፈልግም",
    "common.quickSetup": "ለማዋቀር ከ15 ደቂቃ ያነሰ ይወስዳል",
    "common.rating": "ደረጃ",

    // App
    "app.name": "ሮና",
    "app.tagline": "የሰራተኞች አስተዳደር ሲስተም",

    // Navigation
    "nav.home": "መነሻ",
    "nav.features": "ባህሪያት",
    "nav.about": "ስለ እኛ",
    "nav.contact": "ያግኙን",
    "nav.login": "ግባ",
    "nav.register": "ይመዝገቡ",
    "nav.terms": "የአገልግሎት ውሎች",
    "nav.privacy": "የግላዊነት ፖሊሲ",
    "nav.back": "ተመለስ",

    // Homepage
    "home.hero.title": "የፋብሪካዎን ሰራተኞች በአንድ መተግበሪያ ያስተዳድሩ",
    "home.hero.subtitle": "ሮና የየዕለት ስራዎችን ከፋብሪካ ሰራተኞች ጋር ያቃልል እና እንዲገናኙ ይረዳል፣ ስለዚህ በንግድዎ እድገት ላይ ትኩረት ማድረግ ይችላሉ",
    "home.features.title": "ባህሪያት",
    "home.features.subtitle": "የፋብሪካዎን ሰራተኞች ለማስተዳደር የሚያስፈልግዎ ሁሉ",
    "home.features.description": "ስራዎችን ያቃልሉ፣ ግንኙነትን ያሻሽሉ እና ምርታማነትን ያሳድጉ በኛ አጠቃላይ መፍትሄ",

    // Login
    "login.title": "ግባ",
    "login.subtitle": "መለያዎን ለመጠቀም መረጃዎችዎን ያስገቡ",
    "login.email": "ኢሜይል",
    "login.password": "የይለፍ ቃል",
    "login.forgotPassword": "የይለፍ ቃል ረሳኽ?",
    "login.noAccount": "መለያ የለዎትም?",
    "login.register": "ይመዝገቡ",
    "login.selectRole": "ሚና ይምረጡ",
    "login.worker": "ሰራተኛ",
    "login.admin": "አስተዳዳሪ",
    "login.owner": "ባለቤት",
    "login.otp": "OTP",
    "login.verifying": "በማረጋገጥ ላይ...",
    "login.loggingIn": "በመግባት ላይ...",
    "login.verifyAndLogin": "አረጋግጥ እና ግባ",
    "login.specialAccess": "ልዩ መግቢያ",
    "login.kioskMode": "የኪዮስክ ሁነታ",
    "login.saasAdmin": "SAAS አስተዳዳሪ",

    // SAAS Admin
    "saasAdmin.title": "SAAS አስተዳዳሪ ፖርታል",
    "saasAdmin.subtitle": "ወደ ሮና SAAS አስተዳዳሪ ፖርታል ለመግባት መረጃዎችዎን ያስገቡ",
    "saasAdmin.backToLogin": "ወደ መግቢያ ገጽ ተመለስ",

    // Demo Page
    "demo.title": "ዴሞ ይያዙ",
    "demo.subtitle": "ሮና የፋብሪካዎን የሰራተኞች አስተዳደር እንዴት እንደሚቀይር ይመልከቱ። ቡድናችን ፕላትፎርሙን ያሳይዎታል እና ሁሉንም ጥያቄዎችዎን ይመልሳል።",
    "demo.requestTitle": "ዴሞ ይጠይቁ",
    "demo.requestSubtitle": "ከዚህ በታች ያለውን ቅጽ ይሙሉ እና እኛ እናገኝዎታለን ለእርስዎ ምቹ በሆነ ጊዜ ዴሞ ለማዘጋጀት።",
    "demo.personalizedDemo": "የግል ዴሞ",
    "demo.demoDescription": "ለፋብሪካዎ ልዩ ፍላጎቶች የተበጀ የ30 ደቂቃ ክፍለ ጊዜ",
    "demo.fullName": "ሙሉ ስም",
    "demo.email": "ኢሜይል",
    "demo.companyName": "የኩባንያ ስም",
    "demo.employees": "የሰራተኞች ብዛት",
    "demo.message": "መልእክት",
    "demo.phone": "ስልክ",
    "demo.office": "ቢሮ",
    "demo.location": "አዲስ አበባ፣ ኢትዮጵያ",
    "demo.submitting": "በማስገባት ላይ...",
    "demo.success": "የዴሞ ጥያቄዎ ተልኳል። በቅርቡ እናገኝዎታለን!",

    // Footer
    "footer.copyright": "© 2025 ሮና። ሁሉም መብቶች የተጠበቁ ናቸው።",
    "footer.madeBy": "በነጉስ ማርኬቲንግ የተሰራ",

    // Worker
    "worker.dashboard": "የሰራተኛ ዳሽቦርድ",
    "worker.attendance": "ሰራተኞች",
    "worker.requests": "ጥያቄዎች",
    "worker.schedule": "መርሃ ግብር",
    "worker.payroll": "ክፍያ",
    "worker.profile": "መገለጫ",
    "worker.settings": "ቅንብሮች",
    "worker.notifications": "ማሳወቂያዎች",
    "worker.messages": "መልእክቶች",
    "worker.clockIn": "መግቢያ",
    "worker.clockOut": "መውጫ",
    "worker.leaveRequest": "የእረፍት ጥያቄ",
    "worker.shiftSwap": "የሺፍት ልውውጥ",
    "worker.emergency": "አስቸኳይ",
    "worker.nfcCard": "NFC ካርድ",

    // Admin
    "admin.dashboard": "የአስተዳዳሪ ዳሽቦርድ",
    "admin.workers": "ሰራተኞች",
    "admin.shifts": "ሺፍቶች",
    "admin.attendance": "ሰራተኞች",
    "admin.payroll": "ክፍያ",
    "admin.reports": "ሪፖርቶች",
    "admin.settings": "ቅንብሮች",
    "admin.notifications": "ማሳወቂያዎች",
    "admin.messages": "መልእክቶች",
    "admin.emergency": "አስቸኳይ",
    "admin.multiLocation": "ብዙ ቦታዎች",
    "admin.announcements": "ማስታወቂያዎች",
    "admin.nfcScan": "NFC ስካን",

    // Admin Dashboard
    "admin.welcome": "እንኳን ወደ አስተዳዳሪ ዳሽቦርድ በደህና መጡ",
    "admin.dashboardOverview": "የፋብሪካዎን ስራዎች እና የሰራተኛ ሃይልን ያስተዳድሩ",
    "admin.totalWorkers": "ጠቅላላ ሰራተኞች",
    "admin.activeEmployees": "ንቁ ሰራተኞች",
    "admin.todayAttendance": "የዛሬ መገኘት",
    "admin.present": "ተገኝቷል",
    "admin.late": "ዘግይቷል",
    "admin.absent": "አልተገኘም",
    "admin.openShifts": "ክፍት ሺፍቶች",
    "admin.needsStaffing": "ሰራተኞች ያስፈልጋሉ",
    "admin.pendingRequests": "በመጠባበቅ ላይ ያሉ ጥያቄዎች",
    "admin.awaitingApproval": "ማጽደቅን በመጠበቅ ላይ",
    "admin.emergencies": "አደጋዎች",
    "admin.active": "ንቁ",
    "admin.resolved": "የተፈታ",
    "admin.responseRate": "የምላሽ መጠን",
    "admin.emergencyAlerts": "የአደጋ ማስጠንቀቂያዎች",
    "admin.manageAll": "ሁሉንም ያስተዳድሩ",
    "admin.respond": "ምላሽ ይስጡ",
    "admin.noActiveEmergencies": "ምንም ንቁ አደጋዎች የሉም",
    "admin.pendingApprovals": "በመጠባበቅ ላይ ያሉ ማጽደቆች",
    "admin.attendanceOverview": "የመገኘት አጠቃላይ እይታ",
    "admin.todayShifts": "የዛሬ ሺፍቶች",
    "admin.reviewRequests": "ጥያቄዎችን ይገምግሙ",
    "admin.reviewRequestsDesc": "የሰራተኛ ጥያቄዎችን ያጸድቁ ወይም ይከልክሉ",
    "admin.requestTypes.leave": "የእረፍት ጥያቄ",
    "admin.requestTypes.shift-swap": "የሺፍት ልውውጥ",
    "admin.requestTypes.overtime": "ትርፍ ሰዓት",
    "admin.requestedOn": "የተጠየቀበት ቀን",
    "admin.deny": "ይከልክሉ",
    "admin.approve": "ያጽድቁ",
    "admin.viewAll": "ሁሉንም ይመልከቱ",
    "admin.reviewSelected": "የተመረጡትን ይገምግሙ",
    "admin.timeSlot": "የሰዓት ክፍል",
    "admin.assigned": "የተመደበ",
    "admin.checkedIn": "ገብቷል",
    "admin.manageShift": "ሺፍትን ያስተዳድሩ",
    "admin.viewDetailedAttendance": "ዝርዝር መገኘትን ይመልከቱ",
    "admin.viewAllShifts": "ሁሉንም ሺፍቶች ይመልከቱ",
    "admin.shiftCoverage": "የሺፍት ሽፋን",
    "admin.currentStaffing": "የአሁኑ የሰራተኞች ደረጃዎች እና በቂ ሰራተኞች የሌሏቸው ቦታዎች",
    "admin.scheduled": "የታቀደ",
    "admin.understaffed": "በቂ ሰራተኞች የሌሉት",
    "admin.coverageNeeded": "ሽፋን ያስፈልጋል",
    "admin.eveningShift": "የምሽት ሺፍት",
    "admin.nightShift": "የሌሊት ሺፍት",
    "admin.packaging": "ማሸግ",
    "admin.maintenance": "ጥገና",
    "admin.needAdditionalWorkers": "ተጨማሪ ሰራተኞች ያስፈልጋሉ",
    "admin.assignWorkers": "ሰራተኞችን ይመድቡ",
    "admin.autoAssignAvailableWorkers": "ዝግጁ ሰራተኞችን በራስ-ሰር ይመድቡ",
    "admin.day": "ቀን",
    "admin.week": "ሳምንት",
    "admin.month": "ወር",
    "admin.workerAttendancePatterns": "የሰራተኞች መገኘት ስርዓቶች እና አዝማሚያዎች",
    "admin.onTime": "በሰዓቱ",
    "admin.high": "ከፍተኛ",
    "admin.medium": "መካከለኛ",
    "admin.low": "ዝቅተኛ",
    "admin.id": "መታወቂያ",
    "admin.reporter": "ዘጋቢ",
    "admin.type": "ዓይነት",
    "admin.location": "ቦታ",
    "admin.priority": "ቅድሚያ",
    "admin.status": "ሁኔታ",
    "admin.action": "እርምጃ",
    "admin.critical": "አስፈላጊ",
    "admin.inProgress": "በሂደት ላይ",
    "admin.showing": "እያሳየ ነው",
    "admin.of": "ከ",
    "admin.totalIncidents": "ጠቅላላ ክስተቶች",
    "admin.exportReport": "ሪፖርት ይላኩ",
    "admin.machineryMalfunction": "የማሽን መሰናከል",
    "admin.safetyHazard": "የደህንነት አደጋ",
    "admin.powerOutage": "የኃይል መቋረጥ",
    "admin.chemicalSpill": "የኬሚካል ፍሳሽ",
    "admin.assemblyLine": "የምርት መስመር",
    "admin.packagingArea": "የማሸጊያ ቦታ",
    "admin.building": "ሕንፃ",
    "admin.laboratory": "ላቦራቶሪ",

    // Owner
    "owner.dashboard": "የባለቤት ዳሽቦርድ",
    "owner.finances": "ፋይናንስ",
    "owner.kpi": "KPI",
    "owner.reports": "ሪፖርቶች",
    "owner.settings": "ቅንብሮች",
    "owner.notifications": "ማሳወቂያዎች",
    "owner.messages": "መልእክቶች",
    "owner.emergency": "አስቸኳይ",
    "owner.inventory": "ዕቃዎች",
    "owner.subscription": "ደንበኝነት",
    "owner.branding": "ብራንዲንግ",
    "owner.softwareProblem": "የሶፍትዌር ችግር",
    "owner.nfcScan": "NFC ስካን",

    // Worker Profile
    "profile.title": "የኔ መገለጫ",
    "profile.saveChanges": "ለውጦችን አስቀምጥ",
    "profile.editProfile": "መገለጫን አስተካክል",
    "profile.workerNotFound": "ሰራተኛ አልተገኘም",
    "profile.department": "ክፍል",
    "profile.position": "ቦታ",
    "profile.joinDate": "የተቀላቀሉበት ቀን",
    "profile.nfcCardId": "የNFC ካርድ መታወቂያ",
    "profile.status.label": "ሁኔታ",
    "profile.status.active": "ንቁ",
    "profile.status.inactive": "ንቁ ያልሆነ",
    "profile.status.onLeave": "በእረፍት ላይ",
    "profile.attendanceRate": "የሰራተኛ መገኘት መጠን",
    "profile.target": "ዒላማ",

    "profile.skills.title": "ክህሎቶች",
    "profile.skills.machineOperation": "የማሽን አጠቃቀም",
    "profile.skills.qualityControl": "የጥራት ቁጥጥር",
    "profile.skills.teamLeadership": "የቡድን አመራር",

    "profile.tabs.personal": "የግል መረጃ",
    "profile.tabs.employment": "የቅጥር መረጃ",
    "profile.tabs.qualifications": "ብቃቶች",
    "profile.tabs.performance": "አፈጻጸም",

    "profile.personalInfo.title": "የግል መረጃ",
    "profile.personalInfo.description": "የእርስዎ የግል ዝርዝሮች እና የመገናኛ መረጃ",
    "profile.personalInfo.fullName": "ሙሉ ስም",
    "profile.personalInfo.email": "የኢሜይል አድራሻ",
    "profile.personalInfo.phone": "ስልክ ቁጥር",
    "profile.personalInfo.address": "አድራሻ",
    "profile.personalInfo.emergencyContact": "የአደጋ ጊዜ ተጠሪ",
    "profile.personalInfo.languages": "ቋንቋዎች",

    "profile.employment.title": "የቅጥር ዝርዝሮች",
    "profile.employment.description": "የእርስዎ የቅጥር መረጃ እና የስራ ታሪክ",
    "profile.employment.employeeId": "የሰራተኛ መታወቂያ",
    "profile.employment.currentSchedule": "የአሁኑ መርሃ ግብር",
    "profile.employment.morningShift": "የጠዋት ፈረቃ",
    "profile.employment.afternoonShift": "የከሰዓት ፈረቃ",
    "profile.employment.nightShift": "የሌሊት ፈረቃ",

    "profile.qualifications.title": "ብቃቶች እና ክህሎቶች",
    "profile.qualifications.description": "የእርስዎ ትምህርት፣ የምስክር ወረቀቶች እና የሙያ ክህሎቶች",
    "profile.qualifications.education": "ትምህርት",
    "profile.qualifications.certifications": "የምስክር ወረቀቶች",
    "profile.qualifications.issued": "የተሰጠበት ቀን",
    "profile.education.diploma": "በጨርቃ ጨርቅ ምህንድስና ዲፕሎማ፣ አዲስ አበባ ቴክኖሎጂ ኢንስቲትዩት",
    "profile.certifications.workplaceSafety": "የስራ ቦታ ደህንነት",
    "profile.certifications.machineOperation": "የማሽን አጠቃቀም ደረጃ 2",
    "profile.languages.amharic": "አማርኛ",
    "profile.languages.english": "እንግሊዘኛ",
    "profile.languages.oromo": "ኦሮምኛ",

    "profile.performance.title": "አፈጻጸም እና ሰራተኛ መገኘት",
    "profile.performance.description": "የእርስዎ የአፈጻጸም መለኪያዎች እና የሰራተኛ መገኘት መዝገቦች",
    "profile.performance.rating": "የአፈጻጸም ደረጃ",
    "profile.performance.outOf": "ከ",
    "profile.performance.lastUpdated": "መጨረሻ የተዘመነው",
    "profile.performance.march": "መጋቢት",
    "profile.performance.attendanceSummary": "የሰራተኛ መገኘት ማጠቃለያ",
    "profile.performance.present": "ተገኝቷል",
    "profile.performance.late": "ዘግይቷል",
    "profile.performance.absent": "አልተገኘም",
    "profile.performance.recentAttendance": "የቅርብ ጊዜ መገኘት",
    "profile.performance.date": "ቀን",
    "profile.performance.checkIn": "መግቢያ",
    "profile.performance.checkOut": "መውጫ",
    "profile.performance.status": "ሁኔታ",

    "profile.toast.updated": "መገለጫ ተዘምኗል",
    "profile.toast.updatedDescription": "የእርስዎ የመገለጫ መረጃ በተሳካ ሁኔታ ተዘምኗል።",
  },
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
})

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("en")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    // Check localStorage for saved preference
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "am")) {
      setLanguage(savedLanguage)
    }
    setMounted(true)
  }, [])

  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage)
    localStorage.setItem("language", newLanguage)
  }

  const t = (key: string): string => {
    return translations[language]?.[key as keyof typeof translations.en] || key
  }

  // Avoid hydration mismatch
  if (!mounted) {
    return <>{children}</>
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)

export type { Language }
